# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotr < Formula
  desc "A simple dotfile manager for personal usage."
  homepage "https://github.com/waynezhang/dotr"
  version "0.0.3"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/dotr/releases/download/v0.0.3/dotr_Darwin_x86_64.tar.gz"
      sha256 "42ea1f98b83f65c25c981ec73906e5f256f21e4c2d2883c1799a8a1235b85289"

      def install
        bin.install "dotr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/dotr/releases/download/v0.0.3/dotr_Darwin_arm64.tar.gz"
      sha256 "fafadec4ac94d2f1b94bb740b3a58ec099aa65052775243396b95956a9072024"

      def install
        bin.install "dotr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/dotr/releases/download/v0.0.3/dotr_Linux_x86_64.tar.gz"
        sha256 "0e22476e8017992c479b6f7eff1450373b82314bc0d0c6905bb34660cca63ff6"

        def install
          bin.install "dotr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/dotr/releases/download/v0.0.3/dotr_Linux_arm64.tar.gz"
        sha256 "1ab7a94e87deb36b4690515d69b416b371a5034089de09b2bdd738893de279a4"

        def install
          bin.install "dotr"
        end
      end
    end
  end
end
