# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotr < Formula
  desc "A simple dotfile manager for personal usage."
  homepage "https://github.com/waynezhang/dotr"
  version "0.0.5"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/dotr/releases/download/v0.0.5/dotr_Darwin_x86_64.tar.gz"
      sha256 "c316564c003f7addf1e6a3194573faeca63a6ae46367c6023206ce372c7e144b"

      def install
        bin.install "dotr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/dotr/releases/download/v0.0.5/dotr_Darwin_arm64.tar.gz"
      sha256 "930314b5c7aee2ae60abc73703801a50f8de6850cbd87274c4bba311770aeecc"

      def install
        bin.install "dotr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/dotr/releases/download/v0.0.5/dotr_Linux_x86_64.tar.gz"
        sha256 "6005fe51fafc3224d6b53b9e4176c1642218c1217467035faf84050fa6c85aa4"

        def install
          bin.install "dotr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/dotr/releases/download/v0.0.5/dotr_Linux_arm64.tar.gz"
        sha256 "5ccfa70081769b013aa94bfa0f3f43566b020cfc117228a96890d0ac2f8ac66b"

        def install
          bin.install "dotr"
        end
      end
    end
  end
end
