# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotr < Formula
  desc "A simple dotfile manager for personal usage."
  homepage "https://github.com/waynezhang/dotr"
  version "0.0.2"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/dotr/releases/download/v0.0.2/dotr_Darwin_x86_64.tar.gz"
      sha256 "0ef6ca770cfca42d0a3479c7eae5153ca9c4bf0fe787b8ec3b67eac73630f665"

      def install
        bin.install "dotr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/dotr/releases/download/v0.0.2/dotr_Darwin_arm64.tar.gz"
      sha256 "be9c097a5978219561b846fc245f578837913419c3ab4ff4bdd6505ee28b934f"

      def install
        bin.install "dotr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/dotr/releases/download/v0.0.2/dotr_Linux_x86_64.tar.gz"
        sha256 "0c13c825fa8c40fbd8f21e0cada96c652166ca75cd290983436363833522269e"

        def install
          bin.install "dotr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/dotr/releases/download/v0.0.2/dotr_Linux_arm64.tar.gz"
        sha256 "9b614090f764ae287a5afdc75aef72c7a4f4c37f639aad4f2020677a109ee967"

        def install
          bin.install "dotr"
        end
      end
    end
  end
end
