# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foto < Formula
  desc "Yet another another publishing tool for minimalist photographers."
  homepage "https://github.com/waynezhang/foto"
  version "1.6.1"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/foto/releases/download/v1.6.1/foto_Darwin_x86_64.tar.gz"
      sha256 "81dc35d732cd793dfadcc87134c953a6dd006adcbc77110831b1d1077f41619a"

      def install
        bin.install "foto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/foto/releases/download/v1.6.1/foto_Darwin_arm64.tar.gz"
      sha256 "be411e97f25a30d3468a5d5424b1ce6c05494ec153300ec1738e78acac9c0e24"

      def install
        bin.install "foto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/foto/releases/download/v1.6.1/foto_Linux_x86_64.tar.gz"
        sha256 "5b8b25676c95899ba3175ed56130dabb5ca40168c419a608d3852a2770239d82"

        def install
          bin.install "foto"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/foto/releases/download/v1.6.1/foto_Linux_arm64.tar.gz"
        sha256 "e464e929795f6275bc00bf560afa7ffb5c47a2e04863da3c1f86f8e013da2294"

        def install
          bin.install "foto"
        end
      end
    end
  end
end
