# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foto < Formula
  desc "Yet another another publishing tool for minimalist photographers."
  homepage "https://github.com/waynezhang/foto"
  version "1.5.3"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/foto/releases/download/v1.5.3/foto_Darwin_x86_64.tar.gz"
      sha256 "8fa53ddb7c9901b44a4c8c12391dc60ef3eb48b440e74bbd0ccf4de97cd31f30"

      def install
        bin.install "foto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/foto/releases/download/v1.5.3/foto_Darwin_arm64.tar.gz"
      sha256 "a9a50877fda28a27a6fa6740c9019b81536b33c9d2c4b0687d051fd891f09a7d"

      def install
        bin.install "foto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/foto/releases/download/v1.5.3/foto_Linux_x86_64.tar.gz"
        sha256 "443243577a044e0378b1a5e4f9b234b9063882306b5bd9ef0048a70395999c65"

        def install
          bin.install "foto"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/foto/releases/download/v1.5.3/foto_Linux_arm64.tar.gz"
        sha256 "4412adedeacdff5a5cb6533d3dca8fb38b58aad84f6d643586c4dfd4d264b055"

        def install
          bin.install "foto"
        end
      end
    end
  end
end
