# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foto < Formula
  desc "Yet another another publishing tool for minimalist photographers."
  homepage "https://github.com/waynezhang/foto"
  version "1.1.0"
  license "MIT License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/foto/releases/download/v1.1.0/foto_Darwin_arm64.tar.gz"
      sha256 "d400bf4e64f438e3c415e147d9310d9d12b677420777b86a03ad870fb5cea060"

      def install
        bin.install "foto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/foto/releases/download/v1.1.0/foto_Darwin_x86_64.tar.gz"
      sha256 "35ac5a5d93c3a349f8b8998528333f562a24924269558f2e35de685511d05831"

      def install
        bin.install "foto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/waynezhang/foto/releases/download/v1.1.0/foto_Linux_arm64.tar.gz"
      sha256 "cf85b2ac44e5fb3dddd86de6cccff7f7500dc64ec1543256ca9568f3d492cab5"

      def install
        bin.install "foto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/foto/releases/download/v1.1.0/foto_Linux_x86_64.tar.gz"
      sha256 "580a42bc4522fec5b96f45c88b634c5d4b4155afccca7e431901bfc3a666aa80"

      def install
        bin.install "foto"
      end
    end
  end
end
