# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toyskkserv < Formula
  desc "A toy SKK skkseev. Just made this for fun."
  homepage "https://github.com/waynezhang/toyskkserv"
  version "0.0.3"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.3/toyskkserv_Darwin_x86_64.tar.gz"
      sha256 "524077f848ab90573d3c5a9a61b3e66741ef167de05554918f2aa5c4173ddec4"

      def install
        bin.install "toyskkserv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.3/toyskkserv_Darwin_arm64.tar.gz"
      sha256 "dc088c154c205dd9fa36d1ec8884c9bbf93e98789b6c7bb19127ea8ed2c2e661"

      def install
        bin.install "toyskkserv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.3/toyskkserv_Linux_x86_64.tar.gz"
        sha256 "444009cf7bf9d21466951b55eb4825e8b80cfb63ea69d2ce80cd25245db0f7f5"

        def install
          bin.install "toyskkserv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.3/toyskkserv_Linux_arm64.tar.gz"
        sha256 "ae842b2b9e79385d01efea6456c96703d6a3145874ad37e72b26df30fe71c28e"

        def install
          bin.install "toyskkserv"
        end
      end
    end
  end

  service do
    run [opt_bin/"toyskkserv", "serve"]
    keep_alive true
    log_path var/"log/toyskkserv.log"
    error_log_path var/"log/toyskkserv.log"
  end
end
