# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toyskkserv < Formula
  desc "A toy SKK skkseev. Just made this for fun."
  homepage "https://github.com/waynezhang/toyskkserv"
  version "0.0.7"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.7/toyskkserv_Darwin_x86_64.tar.gz"
      sha256 "c68652b6ed94efdb68527c99a3865fee722792d1946907a595fe24dfa7d87dde"

      def install
        bin.install "toyskkserv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.7/toyskkserv_Darwin_arm64.tar.gz"
      sha256 "bfd3703a7a442748815a2fb416ecd160ea86161e2166e114c68d6710c668bdd2"

      def install
        bin.install "toyskkserv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.7/toyskkserv_Linux_x86_64.tar.gz"
        sha256 "846c79dbf9d4fe8f28bce508d348df45b1f76dbbcc839839ba41ce547b9a7f20"

        def install
          bin.install "toyskkserv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.7/toyskkserv_Linux_arm64.tar.gz"
        sha256 "078b1880cec50ab90865d8b82286bf0fdfc4e3ca9d41c8ed93f33552e5c16f34"

        def install
          bin.install "toyskkserv"
        end
      end
    end
  end

  service do
    run [opt_bin/"toyskkserv", "serve"]
    keep_alive true
    log_path var/"log/toyskkserv.log"
    error_log_path var/"log/toyskkserv.log"
  end
end
