# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toyskkserv < Formula
  desc "A toy SKK skkseev. Just made this for fun."
  homepage "https://github.com/waynezhang/toyskkserv"
  version "0.0.4"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.4/toyskkserv_Darwin_x86_64.tar.gz"
      sha256 "aa8579ae693abbb1903ad4a7de96557bae73729b01f4d32fcb30901452761f85"

      def install
        bin.install "toyskkserv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.4/toyskkserv_Darwin_arm64.tar.gz"
      sha256 "9a88ff1394af0d7f3b1c55e3e0e0edd45b308e6a0653b40a46d7ad5b6b03da81"

      def install
        bin.install "toyskkserv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.4/toyskkserv_Linux_x86_64.tar.gz"
        sha256 "276ad7f8d6f44b98b3afe2eaeee6804712001438a7c8878b882321ca8de6ec21"

        def install
          bin.install "toyskkserv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waynezhang/toyskkserv/releases/download/v0.0.4/toyskkserv_Linux_arm64.tar.gz"
        sha256 "65d29e3e41efd8cf58de8b9e8992d1fa8fcd96b60fcdf354b163c88300d30ffe"

        def install
          bin.install "toyskkserv"
        end
      end
    end
  end

  service do
    run [opt_bin/"toyskkserv", "serve"]
    keep_alive true
    log_path var/"log/toyskkserv.log"
    error_log_path var/"log/toyskkserv.log"
  end
end
