# This file was generated by GoReleaser. DO NOT EDIT.
cask "toyskkserv" do
  name "toyskkserv"
  desc "A toy SKK skkseev. Just made this for fun."
  homepage "https://github.com/waynezhang/toyskkserv"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toyskkserv"

  on_macos do
    on_intel do
      url "https://github.com/waynezhang/toyskkserv/releases/download/v#{version}/toyskkserv_Darwin_x86_64.tar.gz"
      sha256 "a1a1ce64ad1b9d1cd70e009d739fcc0852351a85c5faa959bd2eae3b28b2e88d"
    end
    on_arm do
      url "https://github.com/waynezhang/toyskkserv/releases/download/v#{version}/toyskkserv_Darwin_arm64.tar.gz"
      sha256 "acdb9230e2985768735bab6b356543c81186e054290233b24dcbcc344030ced0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/waynezhang/toyskkserv/releases/download/v#{version}/toyskkserv_Linux_x86_64.tar.gz"
      sha256 "96bb8f80c85a01be2d7d094484a161b4b910f6bf93e9862e63a4dc210248edc6"
    end
    on_arm do
      url "https://github.com/waynezhang/toyskkserv/releases/download/v#{version}/toyskkserv_Linux_arm64.tar.gz"
      sha256 "c79d55c65f4fda21b31d45f37f2776ad955dd61004206a986747f75612b177ea"
    end
  end

  service "run [opt_bin/"toyskkserv", "serve"]
keep_alive true
log_path var/"log/toyskkserv.log"
error_log_path var/"log/toyskkserv.log"
"

  # No zap stanza required
end
